language: node_js
cache:
  directories:
    - node_modules
    - bower_components
node_js:
  - "0.10"
before_install: 
  - npm install -g grunt-cli
  - npm install -g bower
install: 
  - npm install
  - bower install
before_script: grunt build
script: grunt test
